import uuid
import random
import datetime
import argparse
import os
import psycopg2
from typing import List, Tuple
from psycopg2.extras import execute_values
from names_dataset import NameDataset, NameWrapper

# Cache aprceque sinon ca prend 100 ans
_DS = NameDataset(load_first_names=True, load_last_names=True)
_FIRST_KEYS = list(_DS.first_names.keys())
_LAST_KEYS = list(_DS.last_names.keys())


def init_parser() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Populate DB with users, posts and likes (with timestamps)")
    p.add_argument("--users", type=int, default=1000, help="Number of users to create (default: 1000)")
    p.add_argument("--posts-per-user", type=int, default=1, help="Posts created per user (default: 1)")
    p.add_argument("--likes", type=int, default=5000, help="Number of likes to generate (default: 5000)")
    p.add_argument("--start-date", type=str, default=None, help="Start date for timestamps (ISO format) e.g. 2024-01-01")
    p.add_argument("--end-date", type=str, default=None, help="End date for timestamps (ISO format) e.g. 2024-12-31")
    p.add_argument("--out", type=str, default="populate.sql", help="Write SQL to this file instead of executing")
    p.add_argument("--exec", action="store_true", help="Execute directly against DATABASE_URL (requires psycopg2)")
    p.add_argument("--batch-size", type=int, default=500, help="Batch size for DB inserts (default: 500)")
    p.add_argument("--no-dry-run", dest="dry_run", action="store_false", help="Disable dry-run and apply changes when provided (use with --exec)")
    p.set_defaults(dry_run=True)
    return p.parse_args()


def _rand_name() -> Tuple[str, str]:
    first = random.choice(_FIRST_KEYS)
    last = random.choice(_LAST_KEYS)
    print(f"Generated name: {first} {last}")
    return first, last


def generate_users(n: int, created_at: datetime.datetime) -> List[dict]:
    print(f"Starting user generation")
    users = []
    used_names = set()
    for _ in range(n):
        uid = str(uuid.uuid4())
        attempts = 0
        while True:
            first, last = _rand_name()
            name = f"{first} {last}"
            if name not in used_names:
                used_names.add(name)
                break
            attempts += 1
            if attempts >= 50:
                name = f"{first} {last}-{uid[:6]}"
                used_names.add(name)
                break
        email = f"{first.lower()}.{last.lower()}.{uid[:8]}@example.test"
        users.append({
            "id": uid,
            "name": name,
            "email": email,
            "created_at": created_at,
            "updated_at": created_at,
        })
    print(f"Generated {len(users)} users.")
    return users


def generate_posts(users: List[dict], posts_per_user: int, created_at: datetime.datetime) -> List[dict]:
    print("Starting post generation")
    posts = []
    for u in users:
        for _ in range(posts_per_user):
            posts.append({
                "link": "https://example.test/post/" + str(uuid.uuid4()),
                "content": f"Autogenerated post by {u['name']}",
                "created_at": created_at,
                "user_id": u["id"],
                "likes": 0,
            })
    print(f"Generated {len(posts)} posts.")
    return posts


def random_timestamp_between(start: datetime.datetime, end: datetime.datetime) -> datetime.datetime:
    delta = end - start
    seconds = random.randint(0, int(delta.total_seconds()))
    return start + datetime.timedelta(seconds=seconds)


def generate_likes(users: List[dict], posts: List[dict], likes_count: int, start: datetime.datetime, end: datetime.datetime) -> List[dict]:
    print("Starting like generation")
    likes = []
    user_ids = [u["id"] for u in users]
    post_indices = list(range(len(posts)))
    seen = set()
    attempts = 0
    while len(likes) < likes_count and attempts < likes_count * 10:
        attempts += 1
        user_id = random.choice(user_ids)
        post_idx = random.choice(post_indices)
        post = posts[post_idx]
        if post["user_id"] == user_id:
            continue
        key = (user_id, post_idx)
        if key in seen:
            continue
        seen.add(key)
        ts = random_timestamp_between(start, end)
        likes.append({"user_id": user_id, "post_id_idx": post_idx, "created_at": ts})
    likes.sort(key=lambda x: x["created_at"])
    print(f"Generated {len(likes)} likes.")
    return likes


def to_sql(users: List[dict], posts: List[dict], likes: List[dict]) -> str:
    parts = []
    # Users
    for u in users:
        parts.append(
            "INSERT INTO \"user\" (id, name, email, email_verified, image, created_at, updated_at) VALUES ({id}, {name}, {email}, false, NULL, {created}, {updated});".format(
                id=sql_val(u["id"]), name=sql_val(u["name"]), email=sql_val(u["email"]), created=sql_val(u["created_at"]), updated=sql_val(u["updated_at"])  # noqa: E501
            )
        )
    for p in posts:
        parts.append(
            "INSERT INTO post (link, content, created_at, user_id, likes) VALUES ({link}, {content}, {created}, {user_id}, {likes});".format(
                link=sql_val(p["link"]), content=sql_val(p["content"]), created=sql_val(p["created_at"]), user_id=sql_val(p["user_id"]), likes=p["likes"]
            )
        )
    parts.append("\n-- Insert likes (mapping posts by link to find their assigned ids)\n")
    parts.append("WITH inserted_posts AS (SELECT id, link FROM post WHERE link IN (SELECT link FROM post))")
    for l in likes:
        post = posts[l["post_id_idx"]]
        parts.append(
            "INSERT INTO post_like (user_id, post_id, created_at) SELECT {user_id}, id, {created} FROM post WHERE link = {link} LIMIT 1;".format(
                user_id=sql_val(l["user_id"]), created=sql_val(l["created_at"]), link=sql_val(post["link"])
            )
        )
    return "\n".join(parts)


def sql_val(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime.datetime):
        return "'" + v.isoformat(sep=" ") + "'"
    s = str(v).replace("'", "''")
    return "'" + s + "'"


def execute_against_db(sql_statements: str):
    db_url = get_db_url()
    if not db_url:
        raise RuntimeError("No database URL found in environment (DATABASE_URL or POSTGRES_ variables)")
    conn = psycopg2.connect(db_url)
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(sql_statements)
    finally:
        conn.close()


def execute_batches(db_url: str, users: List[dict], posts: List[dict], likes: List[dict], batch_size: int = 500):
    conn = psycopg2.connect(db_url)
    try:
        with conn:
            with conn.cursor() as cur:
                # insert users in batches
                user_vals = [(
                    u["id"], u["name"], u["email"], False, None, u["created_at"], u["updated_at"]
                ) for u in users]
                for i in range(0, len(user_vals), batch_size):
                    batch = user_vals[i:i+batch_size]
                    execute_values(cur, "INSERT INTO \"user\" (id, name, email, email_verified, image, created_at, updated_at) VALUES %s ON CONFLICT (id) DO NOTHING", batch)

                # insert posts in batches
                post_vals = [(
                    p["link"], p["content"], p["created_at"], p["user_id"], p["likes"]
                ) for p in posts]
                all_links = []
                for i in range(0, len(post_vals), batch_size):
                    batch = post_vals[i:i+batch_size]
                    links = [b[0] for b in batch]
                    all_links.extend(links)
                    execute_values(cur, "INSERT INTO post (link, content, created_at, user_id, likes) VALUES %s", batch)

                # fetch inserted post ids by link in batches
                link_to_id = {}
                for i in range(0, len(all_links), batch_size):
                    chunk = all_links[i:i+batch_size]
                    cur.execute("SELECT id, link FROM post WHERE link = ANY(%s)", (chunk,))
                    for row in cur.fetchall():
                        link_to_id[row[1]] = row[0]

                # prepare likes tuples (user_id, post_id, created_at)
                like_vals = []
                for l in likes:
                    post = posts[l["post_id_idx"]]
                    post_id = link_to_id.get(post["link"])
                    if post_id is None:
                        continue
                    like_vals.append((l["user_id"], post_id, l["created_at"]))

                for i in range(0, len(like_vals), batch_size):
                    batch = like_vals[i:i+batch_size]
                    execute_values(cur, "INSERT INTO post_like (user_id, post_id, created_at) VALUES %s ON CONFLICT DO NOTHING", batch)
    finally:
        conn.close()


def get_db_url() -> str | None:
    # prefer explicit DATABASE_URL
    db_url = os.environ.get("DATABASE_URL") or os.environ.get("PG_URI") or os.environ.get("PGDATABASE")
    if db_url:
        return db_url
    # fallback to Drizzle-style env vars if present
    user = os.environ.get("POSTGRES_USER")
    password = os.environ.get("POSTGRES_PASSWORD")
    host = os.environ.get("POSTGRES_HOST")
    port = os.environ.get("POSTGRES_PORT")
    database = os.environ.get("POSTGRES_DB")
    if user and password and host and port and database:
        return f"postgresql://{user}:{password}@{host}:{port}/{database}"
    return None


def main():
    args = init_parser()
    if args.start_date:
        start = datetime.datetime.fromisoformat(args.start_date)
    else:
        start = datetime.datetime.utcnow() - datetime.timedelta(days=90)
    if args.end_date:
        end = datetime.datetime.fromisoformat(args.end_date)
    else:
        end = datetime.datetime.utcnow()

    users = generate_users(args.users, start)
    posts = generate_posts(users, args.posts_per_user, start)
    likes = generate_likes(users, posts, args.likes, start, end)

    sql = to_sql(users, posts, likes)

    # always write SQL file for review
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"Wrote SQL to {args.out}")

    if args.exec:
        if args.dry_run:
            print("Dry-run: no changes applied to database. Use --apply to execute against DATABASE_URL.")
            return
        db_url = os.environ.get("DATABASE_URL") or os.environ.get("PG_URI") or os.environ.get("PGDATABASE")
        if not db_url:
            raise RuntimeError("DATABASE_URL environment variable not found.")
        print("Applying changes to database in batches...")
        execute_batches(db_url, users, posts, likes, batch_size=args.batch_size)
        print("Database update complete.")


if __name__ == "__main__":
    main()
